import p1 from "../img/products/p1.jpg";
import p2 from "../img/products/p2.jpg";
import p3 from "../img/products/p3.jpg";
import p4 from "../img/products/p4.jpg";

export const products = [
  {
    id: 1,
    name: "Embroidered Kurti",
    price: 1299,
    images: [p1, p3, p4], // 👈 array for slider
    description: "A stylish embroidered kurti with intricate embroidery.",
    sizes: ["S", "M", "L", "XL"],
    descriptionDetails: [
      { label: "Fabric", value: "Kurti : Cotton Linen | Bottom :" },
      { label: "Color", value: "Kurti : Pink | Bottom :" },
      { label: "Occasion", value: "Festival Casual Women Wear" },
      { label: "Work", value: "Embroidered" },
      {
        label: "Do note",
        value:
          "Accessories shown in the image are for shooting purpose. There might be some color variation.",
      },
    ],
    reviews: [
      {
        id: 1,
        name: "Priya Sharma",
        avatar: "/avatars/user1.jpg",
        rating: 5,
        comment: "Loved the fabric quality! Perfect fit.",
        date: "2025-08-28",
      },
    ],
  },
  {
    id: 2,
    name: "Onion Pink Embroidered Neck Vatican Kurti Set with Chanderi Jacquard Dupatta",
    price: 1799,
    images: [p2, p4, p1, p3],
    description:
      "Elegant kurti set with dupatta, perfect for festive occasions.",
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 3,
    name: "Casual Tunic",
    price: 999,
    images: [p3, p1],
    description: "Lightweight tunic for everyday casual wear.",
    sizes: ["S", "M", "L"],
    reviews: [],
  },
  {
    id: 4,
    name: "Designer Saree",
    price: 2499,
    images: [p4, p2, p3],
    description: "Premium designer saree with fine fabric and design.",
    sizes: [],
    reviews: [],
  },
  {
    id: 5,
    name: "Embroidered Kurti",
    price: 1299,
    images: [p1, p3],
    description: "Beautiful embroidered kurti with comfortable fabric.",
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 6,
    name: "Kurti Set with Dupatta",
    price: 1799,
    images: [p2, p4],
    description: "Trendy kurti set with dupatta.",
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 7,
    name: "Casual Tunic",
    price: 999,
    images: [p3, p1],
    description: "Simple tunic for everyday comfort.",
    sizes: ["S", "M", "L"],
    reviews: [],
  },
  {
    id: 8,
    name: "Designer Saree",
    price: 2499,
    images: [p4, p2],
    description: "Elegant saree designed for special occasions.",
    sizes: [],
    reviews: [],
  },
  {
    id: 9,
    name: "Embroidered Kurti",
    price: 1299,
    images: [p1, p3],
    description: "Stylish embroidered kurti with premium finishing.",
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 10,
    name: "Kurti Set with Dupatta",
    price: 1799,
    images: [p2, p4],
    description: "Classic kurti set with a dupatta for traditional look.",
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 11,
    name: "Casual Tunic",
    price: 999,
    images: [p3, p1],
    description: "Breathable tunic for daily use.",
    sizes: ["S", "M", "L"],
    reviews: [],
  },
  {
    id: 12,
    name: "Designer Saree",
    price: 2499,
    images: [p4, p2],
    description: "Luxurious saree crafted for elegance.",
    sizes: [],
    reviews: [],
  },
];
